create temporary table purged_instance_ids select id from instance where state = 'purged';
delete from instance_host_map where state = 'purged';
delete from instance_host_map where instance_id in (select id from purged_instance_ids);
delete from instance_label_map where state = 'purged';
delete from instance_label_map where instance_id in (select id from purged_instance_ids);
delete from ip_address_nic_map where state = 'purged';
delete from ip_address_nic_map where nic_id in (select id from nic where instance_id in (select id from purged_instance_ids));
delete from nic where state = 'purged';
delete from nic where instance_id in (select id from purged_instance_ids);
delete from mount where state = 'purged';
delete from mount where instance_id in (select id from purged_instance_ids);
delete from port where state = 'purged';
delete from port where instance_id in (select id from purged_instance_ids);
delete from instance_link where state = 'purged';
delete from instance_link where instance_id in (select id from purged_instance_ids);
delete from instance_link where target_instance_id in (select id from purged_instance_ids);
delete from instance where network_container_id in (select id from purged_instance_ids); 
delete from service_expose_map where state = 'purged';
delete from service_expose_map where instance_id in (select id from purged_instance_ids);
delete from network_service_provider_instance_map where state = 'purged';
delete from network_service_provider_instance_map where instance_id in (select id from purged_instance_ids);
delete from volume_storage_pool_map where state = 'purged';
delete from volume_storage_pool_map where volume_id in (select id from volume where instance_id in (select id from purged_instance_ids));
delete from volume where state = 'purged';
delete from volume where instance_id in (select id from purged_instance_ids);
delete from service_event where state = 'purged';
delete from service_event where healthcheck_instance_id in (select id from healthcheck_instance where instance_id in (select id from purged_instance_ids));
delete from healthcheck_instance_host_map where state = 'purged';
delete from healthcheck_instance_host_map where healthcheck_instance_id in (select id from healthcheck_instance where instance_id in (select id from purged_instance_ids));
delete from healthcheck_instance where state = 'purged';
delete from healthcheck_instance where instance_id in (select id from purged_instance_ids);
delete from instance where id in (select id from purged_instance_ids);
optimize table process_execution;
optimize table process_instance;
optimize table container_event;
optimize table audit_log;
optimize table instance;
optimize table healthcheck_instance;
optimize table healthcheck_instance_host_map;
optimize table service_event;
optimize table volume;
optimize table volume_storage_pool_map;
optimize table network_service_provider_instance_map;
optimize table service_expose_map;
optimize table instance_link;
optimize table port;
optimize table mount;
optimize table nic;
optimize table ip_address_nic_map;
optimize table instance_label_map;
optimize table instance_host_map;
optimize table service_log;
